baseURL = "https://yaikeda.github.io/cuda-examples-blog/"
languageCode = "en-us"
title = "CUDA Examples"
theme = "hugo-PaperMod"

# ç”»åƒãƒ‘ã‚¹ã®è¨­å®š
staticDir = "static"

[pagination]
  pagerSize = 5

[params]
  author = "yaikeda"
  defaultTheme = "light"
  ShowReadingTime = true
  ShowShareButtons = true
  ShareButtons = ["linkedin"]

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/yasunari-ikeda/"

  [params.homeInfoParams]
    Title = "PaperMod's Demo"
    Content = """ğŸ‘‹ Welcome to demo page of Hugo's theme PaperMod!

    - **PaperMod**  is designed to be clean and simple but fast and responsive theme with useful feature-set that enhances UX.

    - Feel free to show your support by giving us a star ğŸŒŸ on GitHub and sharing with your friends and social media .

    - PaperMod is based on theme [Paper](https://github.com/nanxiaobei/hugo-paper/tree/4330c8b12aa48bfdecbcad6ad66145f679a430b3).
    """

[markup]
  [markup.highlight]
    noClasses = false
